### ISSUE TITLE
 Name or service not known

### ISSUE THREAD

**Issue by securiteinfo** [bambish/ScanQLi#5]
Your tools seems to not understand urls with "?" character...

python scanqli.py -u 'http://xxx.xxx.xxx' -r
   ____                   ____    __    _
  / __/ ____ ___ _  ___  / __ \  / /   (_)
 _\ \  / __// _ `/ / _ \/ /_/ / / /__ / /
/___/  \__/ \_,_/ /_//_/\___\_\/____//_/

https://github.com/bambish
https://twitter.com/bambishee

Base URL = http://xxx.xxx.xxx/
HTTPConnectionPool(host='spip.php', port=80): Max retries exceeded with url: /?rubrique24 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb26ce441d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by bambish** [comment]
My last commit should fix the issue.

**EDIT:** My change cause some unexpected effect. I rollback.

**Comment by securiteinfo** [comment]
Bug still present :

http://spip.php?rubrique24
ERROR: Connection Error : HTTPConnectionPool(host='spip.php', port=80): Max retries exceeded with url: /?rubrique24 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b956b9110>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by bambish** [comment]
Normally my last commit fix the bug this time.

**Comment by securiteinfo** [comment]
Fixed ! Good job Bambish !
